### ISSUE TITLE
Top "poster Wrapper" not showing

### ISSUE THREAD

**Issue by aburke20** [kasiimh1/trakt-darkmode#2]
Hey,
so I absolutely LOVE your dark theme, but have two very slight issues.

Basically, when you are playing an episode the top of the page will display a "banner" of the currently playing show, right above the show's timer countdown. However, as soon as I use your theme it disappears.

Also, less important, but the percentage and timer numbers aren't translucent, as before, and so the "percent of the show watched" ends up overlapping the title of the show playing every time.

[Here is a picture](https://imgur.com/a/kwtAxZV)

**Comment by kasiimh1** [comment]
Sorry for not seeing this issue before, if anything else needs fixing let me know!

Should be fixed here: https://github.com/kasiimh1/trakt-darkmode/blob/master/Trakt%20Dark%20Mode.user.js

[Screenshot](https://github.com/kasiimh1/trakt-darkmode/blob/master/Screenshot%202020-11-29%20063149.png) of how it looks now

**Comment by kasiimh1** [comment]
Seem's like issue is still there on Edge and Firefox for some reason, but works on Brave, i will look to fix this asap. Other fixes are working in all 3 browsers i have tested.

**Comment by kasiimh1** [comment]
Never mind it works on all 3, if you are using a extension like darkreader, whitelist the page from having darkreader modify it. Otherwise it will stop the banner from showing up!
