### ISSUE TITLE
watchlist page has white areas

### ISSUE THREAD

**Issue by ashwindeivak** [kasiimh1/trakt-darkmode#5]
https://trakt.tv/users/abeillemdc/watchlist for example, has two white areas
I'm using TamperMonkey on Firefox
![traktdarkgithubexample](https://user-images.githubusercontent.com/62357120/116782885-fd31af80-aa8b-11eb-9d5c-5338bd0ead86.png)

**Comment by kasiimh1** [comment]
Should be fixed now
